name: caniuse
version: v1.3.1
summary: Caniuse command line tool
description: |
 Just what you've always wanted, it's a caniuse command line tool! All the power of caniuse.com with none of the nice UI or interactivity!

grade: stable


apps:
  caniuse:
    command: caniuse
    plugs: [network]

parts:
  caniuse:
    plugin: nodejs
    source: .
